export const en = {
  translation: {
    homeWelcomeTitle: "Keep the world running",
    homeWelcomeSubTitle:
      "When the world goes into lockdown, everything stops. But we can't let people die because of the lockdown. Let's make sure everyone gets what they need to survive.",
    popularDistributors: "Popular Distributors",
    specialNote: "Special note",
    addRequestSubTitle: "State your needs and make a request",
    infoTitle: "info",
    info:
      "Please try to contact the distributors in your area first. Only make a request if you have no other way to obtain the basics. If there are other people in your area who face the same difficulty as you, please add their information also. Do not go around the village to get the information. Use your phone or just shout to the neighbour",
    contactPersonNameInputLabel: "Contact person name",
    numberOfPeopleInputLabel: "Number of people *",
    contactNumberInputLabel: "Contact Number *",
    categoriesInputLabel: "Items needed *",
    cityInputLabel: "City *",
    termsAndConditionDetails:
      "I give my consent to share the above details publicly and I have read and agree to the",
    termsAndConditionLink: "terms and conditions",
    submitButton: "Submit",
    cancelButton: "Cancel",
    addNewRequestInputLabel: "Add request",
    addNewRequestSubtitleInputLabel: "State your needs and make a request",
    addNewDistributorInputLabel: "Add distributor",
    addNewDistributorSubtitleInputLabel: "Enter new distributor details",
    distributorNameInputLabel: "Distributor name *",
    distributorCitiesInputLabel: "City *",
    distributorPhoneNumberInputLabel: "Distributor contact number *",
    distributorWebsiteInputLabel: "Website",
    distributorEmailInputLabel: "Email",
    infoDistributor:
      "Please make sure the content is correct. We will approve distributors only after validating the information. If the information is incorrect, we will not approve it.",
    infoDistributorItems:
      "There should be at least one item or one item pack. Make sure you fill all the required fields denoted by *",
    items: "Items",
    itemsPacks: "Items packs",
    add: "Add",
    nameInputLabel: "Name *",
    removeItem: "Remove",
    submitReview: "Submit for review",
    helpContent: "Showing the most matching 100 cities based on your input.",
    helpItemPacks: "Please add a comma separated list.",
    startType: "Start typing...",
  },
};
