export const si = {
  translation: {
    homeWelcomeTitle: "අවශ්‍යතා ඇති අයට උදව් කරමු.",
    homeWelcomeSubTitle:"කොටසක් ඉදිවෙමින් පවතී",
    addDistributor:"බෙදාහරින්නෙක් එකතු කිරීම",
    popularDistributors:"ජනප්‍රිය බෙදාහරින්නෝ",
    specialNote:"විශේෂ සටහන",
    addRequest:"ඇනවුම් කිරීම",
    addRequestSubTitle:"ඔබේ අවශ්‍යතා සඳහන් කර ඉල්ලීමක් කරන්න",
    infoTitle:"වැදගත්",
    info:"කරුණාකර පළමුව ඔබේ ප්‍රදේශයේ බෙදාහරින්නන් සම්බන්ධ කර ගැනීමට උත්සාහ කරන්න. ඔබට මූලික කරුණු ලබා ගැනීමට වෙනත් ක්‍රමයක් නොමැති නම් පමණක් ඉල්ලීමක් කරන්න. ඔබ හා සමාන දුෂ්කරතාවන්ට මුහුණ දෙන වෙනත් පුද්ගලයින් ඔබේ ප්‍රදේශයේ සිටී නම්, කරුණාකර ඔවුන්ගේ තොරතුරු ද එක් කරන්න. තොරතුරු ලබා ගැනීම සඳහා ගම වටා නොයන්න. ඔබේ දුරකථනය භාවිතා කරන්න හෝ අසල්වැසියාට කෑ ගසන්න",
    contactPersonNameInputLabel:"සම්බන්ධීකරන පුද්ගලයාගේ නම *",
    numberOfPeopleInputLabel:"පුද්ගලයින් ගණන *",
    contactNumberInputLabel:"සම්බන්ධ කරගත හැකි දුරකථන අංකය *",
    categoriesInputLabel:"අවශ්‍ය භාණ්ඩ *",
    cityInputLabel:"නගරය *",
    termsAndConditionDetails:"ඉහත විස්තර ප්‍රසිද්ධියේ බෙදා ගැනීමට මම මගේ කැමැත්ත ලබා දෙන අතර මම නියමයන් සහ කොන්දේසි කියවා එකඟ වී සිටිමි. ",
    termsAndConditionLink:"නියමයන් සහ කොන්දේසි",
    submitButton:"තහවුරු කරන්න",
    cancelButton:"අවලංගු කරන්න",
    addNewRequestInputLabel:"ඇනවුම් කිරීම",
    addNewRequestSubtitleInputLabel:"ඔබේ අවශ්‍යතා සඳහන් කර ඉල්ලීමක් කරන්න",
    addNewDistributorInputLabel:"බෙදාහරින්නෙක් එකතු කිරීම",
    addNewDistributorSubtitleInputLabel:"නව බෙදාහරින්නාගේ තොරතුරු ඇතුලත් කිරීම",
    distributorNameInputLabel:"බෙදාහරින්නාගේ නම *",
    distributorCitiesInputLabel:"බෙදා හැරීමේ ප්‍රදේශ *",
    distributorPhoneNumberInputLabel:"බෙදාහරින්නාගේ දුරකථන අංකය *",
    distributorWebsiteInputLabel:"වෙබ් අඩවිය",
    distributorEmailInputLabel:"විද්යුත් තැපෑල",
    infoDistributor:"කරුණාකර අන්තර්ගතය නිවැරදි බවට වග බලා ගන්න. අපි බෙදාහරින්නන් අනුමත කරන්නේ තොරතුරු වලංගු කිරීමෙන් පසුව පමණි. තොරතුරු වැරදියි නම්, අපි එය අනුමත නොකරමු.",
    infoDistributorItems:"මෙහි අවම වශයෙන් එක් අයිතමයක් හෝ එක් අයිතම පැකට්ටුවක් තිබිය යුතුය. සඳහන් කර ඇති සියලුම ක්ෂේත්‍ර ඔබ පුරවා ඇති බවට වග බලා ගන්න *",
    items:"භාණ්ඩ",
    itemsPacks:"භාණ්ඩ ඇසුරුම්",
    add:"ඇතුලත් කරන්න ",
    removeItem:"ඉවත් කරන්න ",
    submitReview:"සමාලෝචනය සඳහා ඉදිරිපත් කරන්න",
    helpContent:"ඔබගේ වචන  මත පදනම්ව වඩාත්ම ගැලපෙන නගර 100 පෙන්වයි.",
    helpItemPacks:"ලැයිස්තු කොමාවකින් වෙන් කරන්න.",
    startType:"ටයිප් කරන්න...",

  },
};
