export const si = {
  translation: {
    homeWelcomeTitle: "ලෝකය පවත්වාගෙන යන්න උදවු වෙමු",
    homeWelcomeSubTitle:
      "ලෝකය අගුලු දමන්න  යන විට සියල්ල නතර වෙනවා . ඒවුනාට අගුලු දැම්ම කියල අපට මිනිසුන්ට මැරෙන්නට ඉඩදෙන්න බෑ.සෑම කෙනෙකුටම දිවි ගලවා ගැනීමට අවශ්‍ය දේ ලබා ගැනීමට  පුළුවන් වන  බවට අපිට විශ්වාසයි .",
    addDistributor: "බෙදාහරින්නෙක් එකතු කිරීම",
    mostRecentDistributors: "නවතම බෙදාහරින්නන්",
    specialNote: "විශේෂ සටහන",
    addRequest: "ඇනවුම් කිරීම",
    addRequestSubTitle: "ඔබේ අවශ්‍යතා සඳහන් කර ඉල්ලීමක් කරන්න",
    infoTitle: "වැදගත්",
    info:
      "කරුණාකර පළමුව ඔබේ ප්‍රදේශයේ බෙදාහරින්නන් සම්බන්ධ කර ගැනීමට උත්සාහ කරන්න. ඔබට මූලික කරුණු ලබා ගැනීමට වෙනත් ක්‍රමයක් නොමැති නම් පමණක් ඉල්ලීමක් කරන්න. ඔබ හා සමාන දුෂ්කරතාවන්ට මුහුණ දෙන වෙනත් පුද්ගලයින් ඔබේ ප්‍රදේශයේ සිටී නම්, කරුණාකර ඔවුන්ගේ තොරතුරු ද එක් කරන්න. තොරතුරු ලබා ගැනීම සඳහා ගම වටා නොයන්න. ඔබේ දුරකථනය භාවිතා කරන්න හෝ අසල්වැසියාට කෑ ගසන්න",
    contactPersonNameInputLabel: "සම්බන්ධීකරන පුද්ගලයාගේ නම *",
    numberOfPeopleInputLabel: "පුද්ගලයින් ගණන *",
    contactNumberInputLabel: "සම්බන්ධ කරගත හැකි දුරකථන අංකය *",
    categoriesInputLabel: "අවශ්‍ය භාණ්ඩ *",
    cityInputLabel: "නගරය *",
    termsAndConditionDetails:
      "ඉහත විස්තර ප්‍රසිද්ධියේ බෙදා ගැනීමට මම මගේ කැමැත්ත ලබා දෙන අතර මම නියමයන් සහ කොන්දේසි කියවා එකඟ වී සිටිමි. ",
    termsAndConditionLink: "නියමයන් සහ කොන්දේසි",
    privacyPolicy: "රහස්‍යතා ප්‍රතිපත්ති",
    submitButton: "තහවුරු කරන්න",
    cancelButton: "අවලංගු කරන්න",
    addNewRequestInputLabel: "ඇනවුම් කිරීම",
    addNewRequestSubtitleInputLabel: "ඔබේ අවශ්‍යතා සඳහන් කර ඉල්ලීමක් කරන්න",
    addNewDistributorInputLabel: "බෙදාහරින්නෙක් එකතු කිරීම",
    addNewDistributorSubtitleInputLabel:
      "නව බෙදාහරින්නාගේ තොරතුරු ඇතුලත් කිරීම",
    citiesInputLabel: "බෙදා හැරීමේ ප්‍රදේශ *",
    phoneNumberInputLabel: "බෙදාහරින්නාගේ දුරකථන අංකය *",
    websiteInputLabel: "වෙබ් අඩවිය",
    emailInputLabel: "විද්යුත් තැපෑල",
    infoDistributor:
      "කරුණාකර අන්තර්ගතය නිවැරදි බවට වග බලා ගන්න. අපි බෙදාහරින්නන් අනුමත කරන්නේ තොරතුරු වලංගු කිරීමෙන් පසුව පමණි. තොරතුරු වැරදියි නම්, අපි එය අනුමත නොකරමු.",
    infoDistributorItems:
      "මෙහි අවම වශයෙන් එක් අයිතමයක් හෝ එක් අයිතම පැකට්ටුවක් තිබිය යුතුය. සඳහන් කර ඇති සියලුම ක්ෂේත්‍ර ඔබ පුරවා ඇති බවට වග බලා ගන්න *",
    items: "භාණ්ඩ",
    nameInputLabel: "නම *",
    itemsPacks: "භාණ්ඩ ඇසුරුම්",
    add: "තව එකක් ",
    removeItem: "ඉවත් කරන්න ",
    submitReview: "පරීක්ෂා කරන්න දෙන්න ",
    helpContent: "ඔබගේ වචන  මත පදනම්ව වඩාත්ම ගැලපෙන නගර 100 පෙන්වයි.",
    helpItemPacks: "ලැයිස්තු කොමාවකින් වෙන් කරන්න.",
    startType: "ටයිප් කරන්න...",
    bannerImageUrlInputLabel: "ප්‍රවර්ධන ඡයාරූපයේ වෙබ් ලිපිනය(URL)",
    bannerImageUploadDetails: "ඔබට අයිතමයේ විස්තර බැනරයක තිබේ නම්, කරුණාකර එය",
    bannerImageUploadDetailsTwo:
      "වැනි සේවාවකට upload කර 'direct link' එක මෙහි ඇතුලත් කරන්න.",
    priceInputLabel: "මිල",
    bottomGitHubDetails:
      "ඔබ මෘදුකා๐ඝ සංවර්ධකයෙකු නම්, කරුණාකර මෙම ව්‍යාපෘතිය වැඩිදියුණු කිරීමට උදව් කරන්න. GitHub හි ලින්ක් එක සඳහා මෙතනින් පිවිසෙන්න: ",
    contactUs: "අපි හා සම්බන්ධ වන්න ",
    citiesWithMostRequest: "වැඩිපුර ඉල්ලීම් සහිත නගර ",
    latestRequests: "නවතම ඉල්ලීම් ",
    requestForHelp: "මට උදව් අවශ්‍යයි",
    selectCity: "නගරය තෝරන්න",
    selectDistrict: "දිස්ත්‍රික්කය තෝරන්න",
    aboutUsInputLabel: "අපි ගැන ",
    aboutUsSubtitleInputLabel: "අපි කවුද සහ අපි කරන්න උත්සාහ කරන්නේ කුමක්ද.. ",
    contactInputLabel: "අපි හා සම්බන්ධ වන්න",
    howToContactInputLabel: "කොහොමද සම්බන්ධ වෙන්නෙ",
    requestDistributorInputLabel: "බෙදාහරින්නන්",
    requestDistributorSubtitleInputLabel:
      "ඔවුන්ට යාහැකි ස්ථාන හා සැපයුම් කල හැකි දේවල්",
    requestPageInputLabel: "ඉල්ලීම්",
    requestPageSubtitleInputLabel: "මිනිසුන්ට අවශ්‍ය දේවල්",
    specialNoteDetailsHome:
      "මෙම වෙබ් අඩවිය සෑම කෙනෙකුටම නොමිලේ භාවිතා කල හැක.කරුණාකර එහි පවතින හැකියවන් අනිසි ලෙස භාවිතා නොකරන්න. දැනට, සමහර ප්‍රදේශ වලට අවශ්‍ය සියලු භාණ්ඩ ලැබෙමින් පවතින අතර ඔවුනට බෙදාහැරීම්, ජංගම වෙළඳසැල් හා මාර්ගගත වෙළඳසැල් ආදිය ඇත. නමුත් සමහර ප්‍රදේශ සඳහා මෙම කිසිවක් ලැබෙන්නේ නැත. මෙම වෙබ් අඩවියේ ප්‍රධාන ඉලක්කය වන්නේ එවැනි ප්‍රදේශ හඳුනාගෙන සියලු දෙනා එක්ව මෙම අර්බුදයෙන් බේරී සිටිමට බවට වග බලා ගැනීමයි. වැඩිදුර දැනගැනීමට සඳහා පිවිසෙන්න ",
    newDistributorNavBar: "අලුත් බෙදාහරින්නෙක් ",
    surviveTogetherNavBar: "සැවොම එක්ව බේරාගනිමු",
    showMore: "තව පෙන්වන්න...",
    emptyRequestContent:
      "ඉල්ලීම් කිසිවක් හමුවී නොමැත. කරුණාකර ඉවසීමෙන් රැඳී සිටින්න.",
    contactPersonRequestTable: "සම්බන්ධ වන පුද්ගලයා",
    contactNumberRequestTable: "දුරකථන අංකය",
    noOfPeopleRequestTable: "මිනිසුන් ගණන",
    cityRequestTable: "නගරය",
    createdAtTable: "ඉල්ලීම් කල දවස",
    requestItemTable: "ඉල්ලීම් කල භාණ්ඩ",
    termsAndConditionPageInputLabel: "නියමයන් සහ කොන්දේසි",
    termsAndConditionSubtitlePageInputLabel:
      "මෙම වෙබ් අඩවියේ නියමන් සහ කොන්දේසි",
    cookiesTermsAndConditionPage: "කුකීස්",
    "items.nameInputLabel": "නම *",
    "items.categoryInputLabel": "වර්ගය *",
    "items.priceInputLabel": "මිල",
    "items.deliveryFeeInputLabel": "බෙදාහැරීමේ ගාස්තු",
    "itemPacks.nameInputLabel": "නම *",
    "itemPacks.contentInputLabel": "අන්තර්ගතය *",
    "itemPacks.priceInputLabel": "මිල",
    "itemPacks.deliveryFeeInputLabel": "බෙදාහැරීමේ ගාස්තු",
  },
};
