export const GRAPHQL_ENDPOINT = process.env.REACT_APP_GRAPHQL_ENDPOINT;
export const GRAPHQL_WS_ENDPOINT = process.env.REACT_APP_GRAPHQL_WS_ENDPOINT;

export const COUNTRY_ID = process.env.REACT_APP_COUNTRY_ID;
